export HISTFILE="${XDG_CONFIG_HOME}/bash/bash_history"
export STARSHIP_CONFIG="${XDG_CONFIG_HOME}/starship/starship.toml"
export CARGO_HOME="${XDG_DATA_HOME}/cargo"
export RUSTUP_HOME="${XDG_DATA_HOME}/rustup"
export GOPATH="${XDG_DATA_HOME}:-${HOME}/.asdf/shims}/go"
export USER_SCRIPTS_DIR="${XDG_CONFIG_HOME}/bin"
